[package]
name = "remarkable-events"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
tokio = { version = "1.10.1", default-features = false, features = [ "rt", "fs", "io-util" ] }